name: workflow.yml
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Get Version
        id: get_version
        run: |
          CLEAN_ACTOR=$(echo "${{ github.actor }}" | tr -cd '[:alnum:]._-')
          
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "version=$(node ./.github/scripts/get-version.js $CLEAN_ACTOR)" >> "$GITHUB_OUTPUT"
          else
            echo "version=$(node ./.github/scripts/get-version.js)" >> "$GITHUB_OUTPUT"
          fi

  publish-prerelease:
    name: Publish Prerelease Version
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Create Prerelease Version
        run: npm version ${{ needs.get-version.outputs.version }} --no-git-tag-version --allow-same-version

      - name: Pack Prerelease Version
        run: npm pack

      - uses: actions/upload-artifact@v7
        with:
          name: angular-v22-sitemap-generator-${{ needs.get-version.outputs.version }}.tgz
          path: angular-v22-sitemap-generator-${{ needs.get-version.outputs.version }}.tgz

  test-angular22:
    name: Test Angular 22
    needs: [ get-version, publish-prerelease ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/angular22
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - uses: actions/download-artifact@v8
        with:
          name: angular-v22-sitemap-generator-${{ needs.get-version.outputs.version }}.tgz
          path: tests/angular22

      - name: Install Prerelease Version
        run: npm install angular-v22-sitemap-generator-${{ needs.get-version.outputs.version }}.tgz

      - name: Generate Sitemap
        run: npm run test

      - name: Upload Generated Sitemap
        uses: actions/upload-artifact@v7
        with:
          name: angular22-sitemap.xml
          path: tests/angular22/public/sitemap.xml

      - name: Upload Generated Robots.txt
        uses: actions/upload-artifact@v7
        with:
          name: angular22-robots.txt
          path: tests/angular22/public/robots.txt

  analyze-angular22:
    name: Analyze Angular 22 Output
    needs: test-angular22
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - uses: actions/download-artifact@v8
        with:
          name: angular22-sitemap.xml
      - uses: actions/download-artifact@v8
        with:
          name: angular22-robots.txt

      - name: Install dependencies
        run: npm ci

      - name: Analyze Results
        run: node ./.github/scripts/analyze-results.js 22

  publish:
    name: Publish to npm
    needs:
      - analyze-angular22
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Publish
        run: npm publish --tag latest
